import { NodeId } from './constants';

// Number of distance to move when moving nodes.
export const NODES_MOVE_DISTANCE = 5;

// zoom constants for wheel and pinch
export const ZOOM_BASE = 1.2;
export const ZOOM_MIN = 10;
export const ZOOM_MAX = 400;
export const WHEEL_SENSITIVITY = 150;
export const TOUCHPAD_SENSITIVITY = 20;

// deltaMode multipliers (WheelEvent.DOM_DELTA_LINE / DOM_DELTA_PAGE)
// line mode: Firefox reports ~3 lines per tick; CSS spec suggests 1 line ≈ 40px,
//   so 3 × 40 = 120 which is comparable to Chrome's pixel-mode ~100.
// page mode: rare, approximate a page as ~100px for a reasonable zoom step.
export const DELTA_LINE_MULTIPLIER = 40;
export const DELTA_PAGE_MULTIPLIER = 100;

// soft-clamp margin: within this range of ZOOM_MIN / ZOOM_MAX the zoom factor
// is progressively damped so the user feels deceleration instead of an abrupt stop.
export const ZOOM_DAMPING_RANGE = 30;

// touch defer timings (ms)
// node placement: delay so a second finger for pinch can cancel a destructive
//   action (adding a node). shorter delays risk accidental placement.
// radial menu detection: shorter delay because nearby-element lookup is
//   non-destructive and the menu can be easily dismissed.
export const TOUCH_PLACE_DEFER_MS = 150;
export const TOUCH_RADIAL_DEFER_MS = 80;

/**
 * Structure for guide lines when dragging / moving the nodes.
 */
export interface SnapLine {
    /**
     * snap line: ax + by + c = 0
     * generated by node: (x, y)
     */
    a: number;
    b: number;
    c: number;
    node: NodeId;
    x: number;
    y: number;
}

/**
 * Structure for guide points when dragging / moving the nodes.
 */
export interface SnapPoint {
    // snap to the point.
    x: number;
    y: number;

    // from which nodes the snap point is generated (length === 2).
    originalNodesPos: [{ x: number; y: number }, { x: number; y: number }];
}
