import { NodeId } from './constants';

// Number of distance to move when moving nodes.
export const NODES_MOVE_DISTANCE = 5;

// SVG-unit radius within which the line tool snaps the endpoint to a connectable node.
export const TARGET_SNAP_RADIUS = 20;

// Spatial-hash cell size for target snap (move does one map.get(cellKey)).
// Equal to RADIUS: ±R fan-out writes each node into a small neighborhood, so map
// size stays O(nodes) (a few cells per node; ≤ ~9× connectable nodes).
export const TARGET_SNAP_CELL_SIZE = TARGET_SNAP_RADIUS;

/**
 * Structure for guide lines when dragging / moving the nodes.
 */
export interface SnapLine {
    /**
     * snap line: ax + by + c = 0
     * generated by node: (x, y)
     */
    a: number;
    b: number;
    c: number;
    node: NodeId;
    x: number;
    y: number;
}

/**
 * Structure for guide points when dragging / moving the nodes.
 */
export interface SnapPoint {
    // snap to the point.
    x: number;
    y: number;

    // from which nodes the snap point is generated (length === 2).
    originalNodesPos: [{ x: number; y: number }, { x: number; y: number }];
}
