import { ActionReducerMapBuilder, createAction, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { MultiDirectedGraph } from 'graphology';
import { SerializedGraph } from 'graphology-types';
import { NodeAttributes, EdgeAttributes, GraphAttributes } from '../../constants/constants';

export const MAX_UNDO_SIZE = 49;
export type ParamGraph = SerializedGraph<NodeAttributes, EdgeAttributes, GraphAttributes>;

export interface ProjectSnapshot {
    graph: ParamGraph;
    svgViewBoxZoom: number;
    svgViewBoxMin: { x: number; y: number };
}

export type HistoryEntry =
    | {
          kind: 'graph';
          graph: ParamGraph;
      }
    | {
          kind: 'project';
          project: ProjectSnapshot;
      };

/**
 * ParamState contains all the data that a save has, except for the `version` key.
 * Should be persisted and updated as soon as possible when there is a change in the project.
 *
 * `past` and `future` contains the undo and redo stack.
 * It is similar to redux-undo but due to window.graph, we are implementing it again.
 * https://redux.js.org/usage/implementing-undo-history
 * https://redux-toolkit.js.org/usage/immer-reducers
 *
 * https://stackoverflow.com/questions/72807148/how-to-access-state-of-one-slice-in-reducer-of-another-slice-using-redux-toolkit
 * https://stackoverflow.com/questions/61138775/redux-toolkit-have-two-slices-reference-each-others-actions-in-extrareducers
 * https://redux-toolkit.js.org/api/createSlice#extrareducers
 * https://redux.js.org/usage/structuring-reducers/beyond-combinereducers
 *
 * https://stackoverflow.com/questions/63516716/redux-toolkit-is-it-possible-to-dispatch-other-actions-from-the-same-slice-in-o
 * https://stackoverflow.com/questions/61704805/getting-an-error-a-non-serializable-value-was-detected-in-the-state-when-using
 */
export interface ParamState {
    /**
     * Graph generated by `graph.export()`.
     */
    present: ParamGraph;
    past: HistoryEntry[];
    future: HistoryEntry[];
    /**
     * Controls the zoom of the svg.
     * NOTE IT IS SUPER IMPORTANT TO TAKE THIS FACTOR INTO CONSIDERATION
     * IF YOU WANT TO USE THE CORRECT MOUSE POSITION!
     */
    svgViewBoxZoom: number;
    /**
     * The left and top most coordinate.
     */
    svgViewBoxMin: { x: number; y: number };
}

const initialState: ParamState = {
    present: new MultiDirectedGraph<NodeAttributes, EdgeAttributes, GraphAttributes>().export(),
    past: [],
    future: [],
    svgViewBoxZoom: 100,
    svgViewBoxMin: { x: 0, y: 0 },
};

export const applyUndoAction = createAction<HistoryEntry['kind']>('undo');
export const applyRedoAction = createAction<HistoryEntry['kind']>('redo');

const paramSlice = createSlice({
    name: 'param',
    initialState,
    reducers: {
        /**
         * Only set full state in initialization or undo/redo won't work.
         * It relies on changes to be updated by saveGraph.
         */
        setFullState: (state, action: PayloadAction<ParamState>) => {
            return structuredClone(action.payload);
        },
        saveGraph: (state, action: PayloadAction<ParamGraph>) => {
            state.future = [];
            state.past.push({ kind: 'graph', graph: state.present });
            // limit the maximum undo stack size to prevent insane memory usage
            if (state.past.length > MAX_UNDO_SIZE) state.past.shift();
            state.present = structuredClone(action.payload);
        },
        replaceProjectState: (state, action: PayloadAction<ProjectSnapshot>) => {
            state.future = [];
            state.past.push({
                kind: 'project',
                project: {
                    graph: state.present,
                    svgViewBoxZoom: state.svgViewBoxZoom,
                    svgViewBoxMin: state.svgViewBoxMin,
                },
            });
            if (state.past.length > MAX_UNDO_SIZE) state.past.shift();

            state.present = structuredClone(action.payload.graph);
            state.svgViewBoxZoom = action.payload.svgViewBoxZoom;
            state.svgViewBoxMin = structuredClone(action.payload.svgViewBoxMin);
        },
        setSvgViewport: (state, action: PayloadAction<{ zoom: number; min: { x: number; y: number } }>) => {
            state.svgViewBoxZoom = action.payload.zoom;
            state.svgViewBoxMin = action.payload.min;
        },
        setSvgViewBoxZoom: (state, action: PayloadAction<number>) => {
            state.svgViewBoxZoom = action.payload;
        },
        setSvgViewBoxMin: (state, action: PayloadAction<{ x: number; y: number }>) => {
            state.svgViewBoxMin = action.payload;
        },
    },
    extraReducers: (builder: ActionReducerMapBuilder<ParamState>) => {
        builder
            .addCase(applyUndoAction, (state, action) => {
                if (state.past.length === 0) return;
                const previous = state.past[state.past.length - 1]!;
                if (previous.kind !== action.payload) return;
                state.past.pop();

                if (previous.kind === 'graph') {
                    state.future.unshift({ kind: 'graph', graph: state.present });
                    state.present = previous.graph;
                } else {
                    state.future.unshift({
                        kind: 'project',
                        project: {
                            graph: state.present,
                            svgViewBoxZoom: state.svgViewBoxZoom,
                            svgViewBoxMin: state.svgViewBoxMin,
                        },
                    });
                    state.present = previous.project.graph;
                    state.svgViewBoxZoom = previous.project.svgViewBoxZoom;
                    state.svgViewBoxMin = previous.project.svgViewBoxMin;
                }
            })
            .addCase(applyRedoAction, (state, action) => {
                if (state.future.length === 0) return;
                const next = state.future[0]!;
                if (next.kind !== action.payload) return;
                state.future.shift();

                if (next.kind === 'graph') {
                    state.past.push({ kind: 'graph', graph: state.present });
                    state.present = next.graph;
                } else {
                    state.past.push({
                        kind: 'project',
                        project: {
                            graph: state.present,
                            svgViewBoxZoom: state.svgViewBoxZoom,
                            svgViewBoxMin: state.svgViewBoxMin,
                        },
                    });
                    state.present = next.project.graph;
                    state.svgViewBoxZoom = next.project.svgViewBoxZoom;
                    state.svgViewBoxMin = next.project.svgViewBoxMin;
                }
                if (state.past.length > MAX_UNDO_SIZE) state.past.shift();
            });
    },
});

export const { setFullState, saveGraph, replaceProjectState, setSvgViewport, setSvgViewBoxZoom, setSvgViewBoxMin } =
    paramSlice.actions;
export default paramSlice.reducer;
