import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { SerializedGraph } from 'graphology-types';
import { NodeAttributes, EdgeAttributes, GraphAttributes } from '../../constants/constants';

export interface AppState {
    // TODO: Use SerializedGraph<NodeAttributes, EdgeAttributes, GraphAttributes>
    /**
     * Graph generated by `JSON.stringify(graph.export())`.
     */
    graph: string;
    /**
     * Controls the zoom of the svg.
     * NOTE IT IS SUPER IMPORTANT TO TAKE THIS FACTOR INTO CONSIDERATION
     * IF YOU WANT TO USE THE CORRECT MOUSE POSITION!
     */
    svgViewBoxZoom: number;
    /**
     * The left and up most coordinate.
     */
    svgViewBoxMin: { x: number; y: number };
}

const initialState: AppState = {
    graph: '{}',
    svgViewBoxZoom: 100,
    svgViewBoxMin: { x: 0, y: 0 },
};

const appSlice = createSlice({
    name: 'app',
    initialState,
    reducers: {
        setFullState: (state, action: PayloadAction<AppState>) => {
            // https://stackoverflow.com/questions/60002846/how-can-you-replace-entire-state-in-redux-toolkit-reducer
            return { ...action.payload };
        },
        saveGraph: (state, action: PayloadAction<SerializedGraph<NodeAttributes, EdgeAttributes, GraphAttributes>>) => {
            state.graph = JSON.stringify(action.payload);
        },
        setSvgViewBoxZoom: (state, action: PayloadAction<number>) => {
            state.svgViewBoxZoom = action.payload;
        },
        setSvgViewBoxMin: (state, action: PayloadAction<{ x: number; y: number }>) => {
            state.svgViewBoxMin = action.payload;
        },
    },
});

export const { setFullState, saveGraph, setSvgViewBoxZoom, setSvgViewBoxMin } = appSlice.actions;
export default appSlice.reducer;
