name: Release Org

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Release"]  # Name of the workflow to listen to
    types: [completed]                # Trigger when the workflow finishes

jobs:
  release:
    # Only run if the "Build and Release" workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    steps:
      - name: Release
        uses: railmapgen/releaser-org@main
        with:
          app_name: rmp
